import React, { createContext, useContext, useState, useCallback, useEffect } from "react";

type Lang = "zh-TW" | "zh-CN" | "en" | "ja" | "ko" | "th" | "vi" | "fr" | "de" | "es";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  languages: { code: Lang; name: string; nativeName: string }[];
}

const languages: { code: Lang; name: string; nativeName: string }[] = [
  { code: "zh-TW", name: "繁體中文", nativeName: "繁體中文" },
  { code: "zh-CN", name: "簡體中文", nativeName: "简体中文" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "ja", name: "日本語", nativeName: "日本語" },
  { code: "ko", name: "한국어", nativeName: "한국어" },
  { code: "th", name: "ภาษาไทย", nativeName: "ภาษาไทย" },
  { code: "vi", name: "Tiếng Việt", nativeName: "Tiếng Việt" },
  { code: "fr", name: "Français", nativeName: "Français" },
  { code: "de", name: "Deutsch", nativeName: "Deutsch" },
  { code: "es", name: "Español", nativeName: "Español" },
];

const translations: Record<Lang, Record<string, string>> = {
  "zh-TW": {
    "nav.home": "首頁", "nav.spots": "景點", "nav.planner": "行程", "nav.diary": "日記",
    "nav.hotels": "旅館", "nav.flights": "機票", "nav.tools": "工具", "nav.login": "登入",
    "nav.profile": "個人資料", "nav.settings": "設定", "nav.friends": "好友",
    "nav.bookings": "我的預訂", "nav.milestones": "里程碑", "nav.logout": "登出",
    "home.hero.tag": "探索・體驗・記錄",
    "home.hero.title1": "讓旅行成為",
    "home.hero.title2": "生命的詩篇",
    "home.hero.desc": "從規劃到出發，從探索到記錄。Lumina Voyage 陪伴你走過每一段旅途，讓每一次冒險都成為永恆的回憶。",
    "home.hero.explore": "開始探索", "home.hero.plan": "規劃行程",
    "home.features.title": "一站式旅行體驗",
    "home.features.desc": "從靈感到出發，所有你需要的旅行工具",
    "home.destinations.title": "精選目的地",
    "home.destinations.desc": "探索世界各地的熱門旅遊勝地",
    "spots.title": "景點探索", "spots.search": "搜尋景點...",
    "planner.title": "行程規劃", "planner.ai": "AI 智慧規劃",
    "planner.history": "歷史行程", "planner.new": "新增行程",
    "diary.title": "旅遊日記", "diary.write": "撰寫日記",
    "diary.history": "歷史日記", "diary.new": "新增日記",
    "hotels.title": "旅館預訂", "hotels.search": "搜尋旅館",
    "flights.title": "機票查詢", "flights.search": "搜尋航班",
    "tools.title": "旅行工具箱",
    "tools.translate": "翻譯", "tools.currency": "匯率",
    "tools.weather": "天氣", "tools.navigate": "導航",
    "settings.title": "設定", "settings.theme": "外觀主題",
    "settings.language": "介面語言", "settings.notifications": "通知",
    "settings.dark": "深色模式", "settings.light": "淺色模式", "settings.system": "跟隨系統",
    "common.save": "儲存", "common.cancel": "取消", "common.confirm": "確認",
    "common.delete": "刪除", "common.edit": "編輯", "common.search": "搜尋",
    "common.loading": "載入中...", "common.noData": "暫無資料",
    "common.back": "返回", "common.next": "下一步", "common.prev": "上一步",
    "common.submit": "提交", "common.close": "關閉",
    "login.title": "歡迎回來", "login.subtitle": "登入你的 Lumina Voyage 帳號",
    "login.email": "電子郵件", "login.password": "密碼",
    "login.forgot": "忘記密碼？", "login.login": "登入",
    "login.register": "註冊", "login.or": "或使用以下方式登入",
    "login.noAccount": "還沒有帳號？", "login.hasAccount": "已有帳號？",
    "profile.title": "個人資料", "profile.save": "儲存變更",
    "profile.security": "安全設定", "profile.linked": "已連結帳號",
    "friends.title": "好友", "friends.add": "新增好友",
    "friends.scan": "掃碼", "friends.phone": "電話",
    "friends.id": "ID", "friends.number": "數字",
    "bookings.title": "我的預訂", "bookings.flights": "機票",
    "bookings.hotels": "旅館", "bookings.trips": "行程",
    "milestones.title": "旅行里程碑",
    "about.title": "關於我們", "privacy.title": "隱私政策", "terms.title": "服務條款",
  },
  "zh-CN": {
    "nav.home": "首页", "nav.spots": "景点", "nav.planner": "行程", "nav.diary": "日记",
    "nav.hotels": "酒店", "nav.flights": "机票", "nav.tools": "工具", "nav.login": "登录",
    "nav.profile": "个人资料", "nav.settings": "设置", "nav.friends": "好友",
    "nav.bookings": "我的预订", "nav.milestones": "里程碑", "nav.logout": "退出",
    "home.hero.tag": "探索・体验・记录",
    "home.hero.title1": "让旅行成为",
    "home.hero.title2": "生命的诗篇",
    "home.hero.desc": "从规划到出发，从探索到记录。Lumina Voyage 陪伴你走过每一段旅途，让每一次冒险都成为永恒的回忆。",
    "home.hero.explore": "开始探索", "home.hero.plan": "规划行程",
    "home.features.title": "一站式旅行体验",
    "home.features.desc": "从灵感到出发，所有你需要的旅行工具",
    "home.destinations.title": "精选目的地",
    "home.destinations.desc": "探索世界各地的热门旅游胜地",
    "spots.title": "景点探索", "spots.search": "搜索景点...",
    "planner.title": "行程规划", "planner.ai": "AI 智能规划",
    "planner.history": "历史行程", "planner.new": "新增行程",
    "diary.title": "旅游日记", "diary.write": "撰写日记",
    "diary.history": "历史日记", "diary.new": "新增日记",
    "hotels.title": "酒店预订", "hotels.search": "搜索酒店",
    "flights.title": "机票查询", "flights.search": "搜索航班",
    "tools.title": "旅行工具箱",
    "tools.translate": "翻译", "tools.currency": "汇率",
    "tools.weather": "天气", "tools.navigate": "导航",
    "settings.title": "设置", "settings.theme": "外观主题",
    "settings.language": "界面语言", "settings.notifications": "通知",
    "settings.dark": "深色模式", "settings.light": "浅色模式", "settings.system": "跟随系统",
    "common.save": "保存", "common.cancel": "取消", "common.confirm": "确认",
    "common.delete": "删除", "common.edit": "编辑", "common.search": "搜索",
    "common.loading": "加载中...", "common.noData": "暂无数据",
    "common.back": "返回", "common.next": "下一步", "common.prev": "上一步",
    "common.submit": "提交", "common.close": "关闭",
    "login.title": "欢迎回来", "login.subtitle": "登录你的 Lumina Voyage 账号",
    "login.email": "电子邮件", "login.password": "密码",
    "login.forgot": "忘记密码？", "login.login": "登录",
    "login.register": "注册", "login.or": "或使用以下方式登录",
    "login.noAccount": "还没有账号？", "login.hasAccount": "已有账号？",
    "profile.title": "个人资料", "profile.save": "保存更改",
    "profile.security": "安全设置", "profile.linked": "已连接账号",
    "friends.title": "好友", "friends.add": "添加好友",
    "friends.scan": "扫码", "friends.phone": "电话",
    "friends.id": "ID", "friends.number": "数字",
    "bookings.title": "我的预订", "bookings.flights": "机票",
    "bookings.hotels": "酒店", "bookings.trips": "行程",
    "milestones.title": "旅行里程碑",
    "about.title": "关于我们", "privacy.title": "隐私政策", "terms.title": "服务条款",
  },
  en: {
    "nav.home": "Home", "nav.spots": "Spots", "nav.planner": "Planner", "nav.diary": "Diary",
    "nav.hotels": "Hotels", "nav.flights": "Flights", "nav.tools": "Tools", "nav.login": "Login",
    "nav.profile": "Profile", "nav.settings": "Settings", "nav.friends": "Friends",
    "nav.bookings": "My Bookings", "nav.milestones": "Milestones", "nav.logout": "Logout",
    "home.hero.tag": "Explore · Experience · Record",
    "home.hero.title1": "Let Travel Become",
    "home.hero.title2": "A Poem of Life",
    "home.hero.desc": "From planning to departure, from exploration to recording. Lumina Voyage accompanies you through every journey, making every adventure an eternal memory.",
    "home.hero.explore": "Start Exploring", "home.hero.plan": "Plan Trip",
    "home.features.title": "All-in-One Travel Experience",
    "home.features.desc": "From inspiration to departure, all the travel tools you need",
    "home.destinations.title": "Featured Destinations",
    "home.destinations.desc": "Explore popular tourist destinations around the world",
    "spots.title": "Explore Spots", "spots.search": "Search spots...",
    "planner.title": "Trip Planner", "planner.ai": "AI Smart Planning",
    "planner.history": "History", "planner.new": "New Trip",
    "diary.title": "Travel Diary", "diary.write": "Write Diary",
    "diary.history": "History", "diary.new": "New Entry",
    "hotels.title": "Hotel Booking", "hotels.search": "Search Hotels",
    "flights.title": "Flight Search", "flights.search": "Search Flights",
    "tools.title": "Travel Toolbox",
    "tools.translate": "Translate", "tools.currency": "Currency",
    "tools.weather": "Weather", "tools.navigate": "Navigate",
    "settings.title": "Settings", "settings.theme": "Appearance",
    "settings.language": "Language", "settings.notifications": "Notifications",
    "settings.dark": "Dark Mode", "settings.light": "Light Mode", "settings.system": "System",
    "common.save": "Save", "common.cancel": "Cancel", "common.confirm": "Confirm",
    "common.delete": "Delete", "common.edit": "Edit", "common.search": "Search",
    "common.loading": "Loading...", "common.noData": "No Data",
    "common.back": "Back", "common.next": "Next", "common.prev": "Previous",
    "common.submit": "Submit", "common.close": "Close",
    "login.title": "Welcome Back", "login.subtitle": "Sign in to your Lumina Voyage account",
    "login.email": "Email", "login.password": "Password",
    "login.forgot": "Forgot password?", "login.login": "Sign In",
    "login.register": "Sign Up", "login.or": "Or sign in with",
    "login.noAccount": "Don't have an account?", "login.hasAccount": "Already have an account?",
    "profile.title": "Profile", "profile.save": "Save Changes",
    "profile.security": "Security", "profile.linked": "Linked Accounts",
    "friends.title": "Friends", "friends.add": "Add Friend",
    "friends.scan": "Scan", "friends.phone": "Phone",
    "friends.id": "ID", "friends.number": "Number",
    "bookings.title": "My Bookings", "bookings.flights": "Flights",
    "bookings.hotels": "Hotels", "bookings.trips": "Trips",
    "milestones.title": "Travel Milestones",
    "about.title": "About Us", "privacy.title": "Privacy Policy", "terms.title": "Terms of Service",
  },
  ja: {
    "nav.home": "ホーム", "nav.spots": "スポット", "nav.planner": "旅程", "nav.diary": "日記",
    "nav.hotels": "ホテル", "nav.flights": "航空券", "nav.tools": "ツール", "nav.login": "ログイン",
    "nav.profile": "プロフィール", "nav.settings": "設定", "nav.friends": "友達",
    "nav.bookings": "予約一覧", "nav.milestones": "マイルストーン", "nav.logout": "ログアウト",
    "home.hero.tag": "探索・体験・記録",
    "home.hero.title1": "旅を",
    "home.hero.title2": "人生の詩に",
    "home.hero.desc": "計画から出発、探索から記録まで。Lumina Voyageがあなたの旅のすべてに寄り添い、冒険を永遠の思い出にします。",
    "home.hero.explore": "探索開始", "home.hero.plan": "旅程計画",
    "home.features.title": "ワンストップ旅行体験",
    "home.features.desc": "インスピレーションから出発まで、必要な旅行ツールすべて",
    "home.destinations.title": "おすすめの目的地",
    "home.destinations.desc": "世界中の人気観光地を探索",
    "spots.title": "スポット探索", "spots.search": "スポットを検索...",
    "planner.title": "旅程プランナー", "planner.ai": "AIスマートプラン",
    "planner.history": "履歴", "planner.new": "新規作成",
    "diary.title": "旅行日記", "diary.write": "日記を書く",
    "diary.history": "過去の日記", "diary.new": "新規作成",
    "hotels.title": "ホテル予約", "hotels.search": "ホテルを検索",
    "flights.title": "航空券検索", "flights.search": "フライトを検索",
    "tools.title": "旅行ツールボックス",
    "tools.translate": "翻訳", "tools.currency": "為替",
    "tools.weather": "天気", "tools.navigate": "ナビ",
    "settings.title": "設定", "settings.theme": "テーマ",
    "settings.language": "言語", "settings.notifications": "通知",
    "settings.dark": "ダークモード", "settings.light": "ライトモード", "settings.system": "システム",
    "common.save": "保存", "common.cancel": "キャンセル", "common.confirm": "確認",
    "common.delete": "削除", "common.edit": "編集", "common.search": "検索",
    "common.loading": "読み込み中...", "common.noData": "データなし",
    "common.back": "戻る", "common.next": "次へ", "common.prev": "前へ",
    "common.submit": "送信", "common.close": "閉じる",
    "login.title": "おかえりなさい", "login.subtitle": "Lumina Voyageアカウントにログイン",
    "login.email": "メール", "login.password": "パスワード",
    "login.forgot": "パスワードを忘れた？", "login.login": "ログイン",
    "login.register": "新規登録", "login.or": "または以下でログイン",
    "login.noAccount": "アカウントをお持ちでない？", "login.hasAccount": "アカウントをお持ちの方",
    "profile.title": "プロフィール", "profile.save": "変更を保存",
    "profile.security": "セキュリティ", "profile.linked": "連携アカウント",
    "friends.title": "友達", "friends.add": "友達追加",
    "friends.scan": "スキャン", "friends.phone": "電話",
    "friends.id": "ID", "friends.number": "数字",
    "bookings.title": "予約一覧", "bookings.flights": "航空券",
    "bookings.hotels": "ホテル", "bookings.trips": "旅程",
    "milestones.title": "旅のマイルストーン",
    "about.title": "私たちについて", "privacy.title": "プライバシーポリシー", "terms.title": "利用規約",
  },
  ko: {
    "nav.home": "홈", "nav.spots": "명소", "nav.planner": "일정", "nav.diary": "일기",
    "nav.hotels": "호텔", "nav.flights": "항공권", "nav.tools": "도구", "nav.login": "로그인",
    "nav.profile": "프로필", "nav.settings": "설정", "nav.friends": "친구",
    "nav.bookings": "내 예약", "nav.milestones": "마일스톤", "nav.logout": "로그아웃",
    "home.hero.tag": "탐험・체험・기록",
    "home.hero.title1": "여행을",
    "home.hero.title2": "삶의 시로",
    "home.hero.desc": "계획부터 출발, 탐험부터 기록까지. Lumina Voyage가 모든 여정을 함께하며 모험을 영원한 추억으로 만듭니다.",
    "home.hero.explore": "탐험 시작", "home.hero.plan": "일정 계획",
    "spots.title": "명소 탐험", "spots.search": "명소 검색...",
    "tools.title": "여행 도구",
    "tools.translate": "번역", "tools.currency": "환율",
    "tools.weather": "날씨", "tools.navigate": "내비",
    "settings.title": "설정", "settings.theme": "테마",
    "settings.language": "언어", "settings.dark": "다크 모드",
    "settings.light": "라이트 모드", "settings.system": "시스템",
    "common.save": "저장", "common.cancel": "취소", "common.confirm": "확인",
    "login.title": "환영합니다", "login.login": "로그인", "login.register": "회원가입",
    "about.title": "소개", "privacy.title": "개인정보처리방침", "terms.title": "이용약관",
  },
  th: {
    "nav.home": "หน้าแรก", "nav.spots": "สถานที่", "nav.planner": "แผนการ", "nav.diary": "ไดอารี่",
    "nav.hotels": "โรงแรม", "nav.flights": "ตั๋วเครื่องบิน", "nav.tools": "เครื่องมือ", "nav.login": "เข้าสู่ระบบ",
    "settings.title": "ตั้งค่า", "settings.language": "ภาษา",
    "settings.dark": "โหมดมืด", "settings.light": "โหมดสว่าง",
    "common.save": "บันทึก", "common.cancel": "ยกเลิก",
    "login.title": "ยินดีต้อนรับ", "login.login": "เข้าสู่ระบบ",
    "about.title": "เกี่ยวกับเรา",
  },
  vi: {
    "nav.home": "Trang chủ", "nav.spots": "Điểm đến", "nav.planner": "Lịch trình", "nav.diary": "Nhật ký",
    "nav.hotels": "Khách sạn", "nav.flights": "Vé máy bay", "nav.tools": "Công cụ", "nav.login": "Đăng nhập",
    "settings.title": "Cài đặt", "settings.language": "Ngôn ngữ",
    "settings.dark": "Chế độ tối", "settings.light": "Chế độ sáng",
    "common.save": "Lưu", "common.cancel": "Hủy",
    "login.title": "Chào mừng", "login.login": "Đăng nhập",
    "about.title": "Về chúng tôi",
  },
  fr: {
    "nav.home": "Accueil", "nav.spots": "Lieux", "nav.planner": "Planifier", "nav.diary": "Journal",
    "nav.hotels": "Hôtels", "nav.flights": "Vols", "nav.tools": "Outils", "nav.login": "Connexion",
    "settings.title": "Paramètres", "settings.language": "Langue",
    "settings.dark": "Mode sombre", "settings.light": "Mode clair",
    "common.save": "Enregistrer", "common.cancel": "Annuler",
    "login.title": "Bienvenue", "login.login": "Se connecter",
    "about.title": "À propos",
  },
  de: {
    "nav.home": "Startseite", "nav.spots": "Orte", "nav.planner": "Planer", "nav.diary": "Tagebuch",
    "nav.hotels": "Hotels", "nav.flights": "Flüge", "nav.tools": "Werkzeuge", "nav.login": "Anmelden",
    "settings.title": "Einstellungen", "settings.language": "Sprache",
    "settings.dark": "Dunkelmodus", "settings.light": "Hellmodus",
    "common.save": "Speichern", "common.cancel": "Abbrechen",
    "login.title": "Willkommen", "login.login": "Anmelden",
    "about.title": "Über uns",
  },
  es: {
    "nav.home": "Inicio", "nav.spots": "Lugares", "nav.planner": "Planificar", "nav.diary": "Diario",
    "nav.hotels": "Hoteles", "nav.flights": "Vuelos", "nav.tools": "Herramientas", "nav.login": "Iniciar sesión",
    "settings.title": "Configuración", "settings.language": "Idioma",
    "settings.dark": "Modo oscuro", "settings.light": "Modo claro",
    "common.save": "Guardar", "common.cancel": "Cancelar",
    "login.title": "Bienvenido", "login.login": "Iniciar sesión",
    "about.title": "Sobre nosotros",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem("lumina_lang");
    return (stored as Lang) || "zh-TW";
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("lumina_lang", l);
    document.documentElement.lang = l;
  }, []);

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] || translations["zh-TW"]?.[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
